### ISSUE TITLE
Could not recieve token

### ISSUE THREAD

**Issue by amihaylov** [ilijamt/express-jwt-auth-mongoose#2]
What is working: 
- creating user via create_user.js
- error handling for unauthorised access and wrong user/password

What is not:
- when user and password are correct, I constantly receive error 500. That is independent of node, express or jwt version. Tried with node 0.12.7 and 4.1.0, jwt 0.4.1 and latest version but no matter what server throws error 500. Actually all jwt versions prior 4 are deprecated for security reasons - https://auth0.com/blog/2015/03/31/critical-vulnerabilities-in-json-web-token-libraries/

**Comment by phil-hudson** [comment]
+1 for this. I'm getting the same errors

**Comment by amihaylov** [comment]
Actually after debugging I figured out I have to have redis installed and running. After that everything is fine. For more info see this thread - http://stackoverflow.com/questions/8754304/redis-connection-to-127-0-0-16379-failed-connect-econnrefused
